-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 09:37:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedor` (
  `id_proveedor` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `fax` VARCHAR(12) NULL,
  `NIF` VARCHAR(9) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` TINYINT(5) NOT NULL,
  `piso` VARCHAR(4) NULL,
  `puerta` VARCHAR(4) NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`cliente` (
  `id_cliente` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `cliente_id_recomend` TINYINT(4) UNSIGNED NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` TINYINT(5) NOT NULL,
  `piso` VARCHAR(4) NULL,
  `puerta` VARCHAR(4) NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_cliente1_idx` (`cliente_id_recomend` ASC),
  CONSTRAINT `fk_cliente_cliente1`
    FOREIGN KEY (`cliente_id_recomend`)
    REFERENCES `optica`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`empleado` (
  `id_empleado` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`marca` (
  `id_marca` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `proveedor_id` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_marca`, `proveedor_id`),
  INDEX `fk_marca_proveedor1_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_marca_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `optica`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`gafas` (
  `id_gafas` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gradua_dch` FLOAT NOT NULL,
  `gradua_izq` FLOAT NOT NULL,
  `montura` ENUM('flotante', 'pasta', 'metalica') NOT NULL,
  `color_montura` VARCHAR(20) NOT NULL,
  `color_cristal_dch` VARCHAR(20) NOT NULL,
  `color_cristal_izq` VARCHAR(20) NOT NULL,
  `precio` FLOAT NOT NULL,
  `marca_id` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_gafas`, `marca_id`),
  INDEX `fk_gafas_marca1_idx` (`marca_id` ASC),
  CONSTRAINT `fk_gafas_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `optica`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`venta` (
  `id_venta` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `cliente_id` TINYINT(4) UNSIGNED NOT NULL,
  `empleado_id` TINYINT(4) UNSIGNED NOT NULL,
  `gafas_id` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venta`, `cliente_id`, `empleado_id`, `gafas_id`),
  INDEX `fk_venta_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_venta_empleado1_idx` (`empleado_id` ASC),
  INDEX `fk_venta_gafas1_idx` (`gafas_id` ASC),
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `optica`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `optica`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_gafas1`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `optica`.`gafas` (`id_gafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/* INSERTAR DATOS*/
/* Datos tabla proveedor */
INSERT INTO proveedor (nombre, telefono, fax, NIF,calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES ('Gafa Pasta SL','654321456','654321456','78654321k','c/ Gran',45, NULL, NULL, 'La Garriga' , 08530, 'Espanya');
INSERT INTO proveedor (nombre, telefono, fax, NIF,calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES ('Gafas Molonguis SA','609876543', NULL,'08754321d','c/ Ramón Pascual',17, '2n', '3A', 'La Garriga' , 08530, 'Espanya');
INSERT INTO proveedor (nombre, telefono, fax, NIF,calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES ('Optigafas SL','615638754',NULL,'35892096g','c/ Calabria',23, NULL, NULL, 'La Garriga' , 08530, 'Espanya');
INSERT INTO proveedor (nombre, telefono, fax, NIF,calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES ('Ni 3 en un burro SL','609653298',NULL,'25679402j','c/ de la Sinia',87, '1', '3', 'La Garriga' , 08530, 'Espanya');

/* Datos tabla cliente */
INSERT INTO cliente (nombre, telefono, mail, fecha_alta, cliente_id_recomend, calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES('Carla', '677654210', 'mail@mail.algo', '2022/02/01', NULL,'Passeig dels Til·lers',46, NULL, NULL, 'La Garriga' , 08530, 'Espanya');
INSERT INTO cliente (nombre, telefono, mail, fecha_alta, cliente_id_recomend, calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES('Laura', '609345276', 'mail@mail.algo', '2022/01/25', NULL,'c/ Santa Digna',14, NULL, NULL, 'La Garriga' , 08530, 'Espanya');
INSERT INTO cliente (nombre, telefono, mail, fecha_alta, cliente_id_recomend, calle, numero, piso, puerta, ciudad, codigo_postal,pais) VALUES('Marc', '623567890', 'mail@mail.algo', '2022/03/27', NULL,'c/ Banys',56, NULL, NULL, 'La Garriga' , 08530, 'Espanya');

/* Datos tabla empleado */
INSERT INTO empleado (nombre) VALUES ('Júlia');
INSERT INTO empleado (nombre) VALUES ('Narcís');
INSERT INTO empleado (nombre) VALUES ('Tània');
INSERT INTO empleado (nombre) VALUES ('Lucia');

/* Datos tabla marca*/
INSERT INTO marca (nombre,proveedor_id) VALUES ('Polaroid', 1);
INSERT INTO marca (nombre,proveedor_id) VALUES ('Munich', 2);
INSERT INTO marca (nombre,proveedor_id) VALUES ('Police', 3);
INSERT INTO marca (nombre,proveedor_id) VALUES ('Persol', 4);

/* Datos tabla gafas*/
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(1.25,0,'pasta','Lila','transparente','transparente',99.9,1);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(0,1.75,'flotante','Verde limón','Coyote','Coyote',150,2);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(1.15,0.55,'metálica','Amarillo','Polarizado','Polarizado',299,3);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(0.10,0.25,'flotante','Marrón leopardo','Arena','Arena',50,3);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(0.75,1.75,'pasta','negor','Negro','Negro',90.9,4);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(1.50,1.25,'metálica','Rojo','Transparente','Transparente',120.5,2);
INSERT INTO gafas (gradua_dch,gradua_izq,montura,color_montura,color_cristal_dch,color_cristal_izq,precio,marca_id) VALUES(1.75,1.75,'pasta','Blanco','Arena','Arena',300,3);

/* Datos tabla venta*/
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/02/01',1,3,3);
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/03/15',1,2,1);
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/04/05',1,4,4);
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/01/25',2,1,7);
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/04/03',2,1,5);
INSERT INTO venta (fecha_venta,cliente_id,empleado_id,gafas_id) VALUE ('2022/03/27',3,2,2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* Queries Optica*/
SELECT COUNT(venta.id_venta) FROM venta WHERE cliente_id = 1;
SELECT DISTINCT * FROM gafas INNER JOIN venta ON gafas.id_gafas = venta.gafas_id WHERE empleado_id = 1 AND fecha_venta BETWEEN '2022-01-01' AND '2022-12-31';
SELECT DISTINCT id_proveedor, proveedor.nombre FROM proveedor LEFT JOIN marca ON proveedor.id_proveedor = marca.proveedor_id LEFT JOIN gafas ON marca.id_marca = gafas.marca_id LEFT JOIN venta ON gafas.id_gafas = venta.gafas_id WHERE venta.id_venta;
